import {useCallback,useEffect,useState} from 'react';
import {Box,Server,Network,Zap,Wind,Search,RotateCcw,Layers,ArrowUpRight,Focus,X,ChevronRight,Eye,SlidersHorizontal} from 'lucide-react';
import DetailExplorer from './DetailExplorer';
import Scene,{type SceneState} from './Scene';
import {roomPanels,type RoomFloorMode} from './room-floor';
import {rackSlots} from './atlas';
import {equipment,systems,searchEquipment,type System} from './atlas';
const icons={racks:Box,compute:Server,network:Network,power:Zap,cooling:Wind};
const initial:SceneState={visible:systems.map(s=>s.id),selected:null,isolate:false,explode:0,paths:false,openServers:true,floorMode:'raised',floorCutaway:false,liftedPanels:[],clearances:false,view:'perspective',reset:0};
export default function App(){
 const readExplorer=()=>location.hash==='#server'?'server':location.hash==='#floor'?'floor':null;
 const [explorer,setExplorer]=useState<'server'|'floor'|null>(readExplorer);
 useEffect(()=>{const sync=()=>setExplorer(readExplorer());window.addEventListener('hashchange',sync);return()=>window.removeEventListener('hashchange',sync);},[]);
 const openExplorer=useCallback((next:'server'|'floor'|null)=>{location.hash=next??'room';setExplorer(next);},[]);
 const closeExplorer=useCallback(()=>openExplorer(null),[openExplorer]);
 const [state,setState]=useState<SceneState>(initial),[query,setQuery]=useState(''),[mobile,setMobile]=useState(false),[collapsed,setCollapsed]=useState(false),[settings,setSettings]=useState(false),[panel,setPanel]=useState(roomPanels.find(p=>!p.occupied&&p.x>3&&p.z>3)!.id),[notice,setNotice]=useState('');
 const selected=equipment.find(e=>e.id===state.selected),results=searchEquipment(query,state.visible);
 function choose(id:string){setSettings(false);setCollapsed(false);const item=equipment.find(e=>e.id===id)!;setState(s=>({...s,selected:id,isolate:false,visible:s.visible.includes(item.system)?s.visible:[...s.visible,item.system]}));setMobile(false);}
 function toggle(id:System){setState(s=>({...s,visible:s.visible.includes(id)?s.visible.filter(x=>x!==id):[...s.visible,id],isolate:false,selected:null}));}
 function liftPanel(id:string){const p=roomPanels.find(p=>p.id===id);if(!p||state.floorMode!=='raised')return;if(p.occupied){setNotice(`${p.name} supports equipment; choose an unloaded service panel.`);return;}setPanel(id);setNotice(`${p.name} ${state.liftedPanels.includes(id)?'reseated':'lifted'}.`);setState(s=>({...s,liftedPanels:s.liftedPanels.includes(id)?s.liftedPanels.filter(p=>p!==id):[...s.liftedPanels,id]}));}
 function reset(){setNotice('');setState(s=>({...initial,reset:s.reset+1}));setQuery('');}
 if(explorer)return <DetailExplorer kind={explorer} onClose={closeExplorer}/>;
 return <main className="atlas">
  <header className="masthead"><div className="brand"><Box size={26} strokeWidth={1.5}/><div><h1>Datacenter Atlas</h1><p>AN INTERACTIVE INFRASTRUCTURE EXPLORER</p></div></div><nav className="explorer-nav" aria-label="Detailed explorers"><button onClick={()=>openExplorer('server')}>Inside a server</button><button onClick={()=>openExplorer('floor')}>Floor systems</button><button aria-pressed={settings} onClick={()=>setSettings(v=>!v)}>Room settings</button></nav></header>
  <div className="workspace">
   <aside className={`sidebar ${mobile?'open':''}`} aria-label="Equipment explorer">
    <div className="side-title"><span>Explore the systems</span><button className="mobile-close icon" aria-label="Close explorer" onClick={()=>setMobile(false)}><X size={18}/></button><Layers size={17} className="desktop"/></div>
    <div className="system-list">{systems.map(s=>{const Icon=icons[s.id];return <button key={s.id} className={`system ${state.visible.includes(s.id)?'enabled':''}`} aria-pressed={state.visible.includes(s.id)} onClick={()=>toggle(s.id)}><Icon size={19} className={`tone-${s.id}`}/><span><strong>{s.name}</strong><small>{s.description}</small></span><span className="count">{equipment.filter(e=>e.system===s.id).length}</span><span className="check">{state.visible.includes(s.id)?'✓':'−'}</span></button>;})}</div>
    <div className="inventory-head"><h2>Equipment index</h2><span>{results.length}</span></div>
    <label className="search-label" htmlFor="search">Find equipment</label><div className="search"><Search size={16}/><input id="search" placeholder="Name, rack, or type…" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button className="icon" aria-label="Clear search" onClick={()=>setQuery('')}><X size={14}/></button>}</div>
    <div className="inventory">{results.map(e=><button key={e.id} className={`inventory-item ${state.selected===e.id?'chosen':''}`} onClick={()=>choose(e.id)} aria-pressed={state.selected===e.id}><span className={`dot tone-${e.system}`}/><span>{e.name}<small>{e.kind}</small></span><ChevronRight size={14}/></button>)}{!results.length&&<div className="empty"><p>No equipment matches these filters.</p><button onClick={reset}>Reset filters</button></div>}</div>
    <div className="sidebar-foot"><span className="mono">REFERENCE MODEL / 01</span><p>Generic equipment. No live telemetry.</p></div>
   </aside>
   <section className="viewport" aria-label="Datacenter visualization">
    <Scene state={state} onSelect={choose} onPanel={liftPanel}/>
    <div className="room-label"><span className="eyebrow">FACILITY / SAMPLE 01</span><h2>The server room</h2><p>{state.isolate?'Floor hidden during isolation':state.explode>0?'Floor hidden in separated view':state.floorMode==='raised'?`Raised floor · ${state.liftedPanels.length} panels lifted`:'Slab floor · equipment at slab level'}</p></div>
    <div className="view-switch" aria-label="Camera view"><button aria-pressed={state.view==='perspective'} onClick={()=>setState(s=>({...s,view:'perspective'}))}>3D view</button><button aria-pressed={state.view==='top'} onClick={()=>setState(s=>({...s,view:'top'}))}>Top view</button></div>
    <button className="mobile-explore" onClick={()=>setMobile(!mobile)}><SlidersHorizontal size={17}/>Explore equipment</button>
    {!state.visible.length&&<div className="no-layers"><p>All systems are hidden.</p><button onClick={reset}>Show systems</button></div>}
    {!settings&&selected&&collapsed?<article className="inspector compact" aria-label="Selected equipment"><h2>{selected.name}</h2><button onClick={()=>setCollapsed(false)}>Show details</button><button className="icon" aria-label="Close equipment details" onClick={()=>setState(s=>({...s,selected:null,isolate:false}))}><X size={17}/></button></article>:!settings&&selected&&<article className="inspector" aria-label="Selected equipment"><div className="inspector-top"><span className={`eyebrow tone-${selected.system}`}>{selected.kind}</span><button className="icon" aria-label="Close equipment details" onClick={()=>setState(s=>({...s,selected:null,isolate:false}))}><X size={17}/></button></div><h2>{selected.name}</h2><span className="mono id">{selected.id}</span>{selected.system==='compute'&&<button className="isolate" onClick={()=>openExplorer('server')}>Explore server internals<ArrowUpRight size={15}/></button>}<p>{selected.description}</p>{selected.system==='racks'&&<details className="rack-occupancy"><summary>Rack unit map · {rackSlots(selected.id).filter(s=>s.equipmentId).length}/42U occupied</summary><p>Numbered from bottom to top. Empty mounting units have blanking panels.</p><ol reversed>{[...rackSlots(selected.id)].reverse().map(slot=><li key={slot.u}><span>U{slot.u}</span>{slot.equipmentId?<button onClick={()=>choose(slot.equipmentId!)}>{equipment.find(e=>e.id===slot.equipmentId)?.name}</button>:<span>Blanking panel</span>}</li>)}</ol></details>}<dl>{Object.entries(selected.specs).map(([key,value])=><div key={key}><dt>{key}</dt><dd>{value}</dd></div>)}</dl><button className="isolate" aria-pressed={state.isolate} onClick={()=>{setCollapsed(!state.isolate);setState(s=>({...s,isolate:!s.isolate}));}}>{state.isolate?<Eye size={16}/>:<Focus size={16}/>} {state.isolate?'Show environment':'Isolate equipment'}<ArrowUpRight size={15}/></button></article>}
    {settings&&<section className="inspector room-settings" aria-label="Room settings"><div className="inspector-top"><h2>Floor & rack settings</h2><button className="icon" aria-label="Close room settings" onClick={()=>setSettings(false)}><X size={17}/></button></div><label>Floor architecture<select value={state.floorMode} onChange={e=>{setNotice('');setState(s=>({...s,floorMode:e.target.value as RoomFloorMode,liftedPanels:[],floorCutaway:false}));}}><option value="raised">Raised access floor</option><option value="slab">Structural slab</option></select></label><label className="setting-check"><input type="checkbox" disabled={state.floorMode==='slab'} checked={state.floorCutaway} onChange={e=>setState(s=>({...s,floorCutaway:e.target.checked}))}/>Cut away unloaded panels</label><p>Cutaway exposes the support grid and slab. Panels under equipment stay seated.</p><label>Service panel<select disabled={state.floorMode==='slab'} value={panel} onChange={e=>setPanel(e.target.value)}>{roomPanels.filter(p=>!p.occupied).map(p=><option key={p.id} value={p.id}>{p.name}{state.liftedPanels.includes(p.id)?' · lifted':''}</option>)}</select></label><button disabled={state.floorMode==='slab'} onClick={()=>liftPanel(panel)}>{state.liftedPanels.includes(panel)?'Reseat selected panel':'Lift selected panel'}</button><button disabled={!state.liftedPanels.length} onClick={()=>{setState(s=>({...s,liftedPanels:[]}));setNotice('All lifted panels reseated.');}}>Reseat all panels</button><p>You can also click unloaded panels in the room. {state.liftedPanels.length} lifted.</p><label className="setting-check"><input type="checkbox" checked={state.clearances} onChange={e=>setState(s=>({...s,clearances:e.target.checked}))}/>Service clearance guides</label><p>Amber front / green rear zones are illustrative, not approved service distances. Floor and guides hide while equipment is separated. Floor layers also hide during equipment isolation.</p><p><strong>Load capacities unspecified.</strong> Slab, panel, concentrated and rolling loads need separate assessment.</p><button onClick={()=>{setSettings(false);openExplorer('floor');}}>Explore floor components</button></section>}
    <div className="room-status" role="status">{notice}</div>
    <div className="bottom-controls"><div className="explode"><label htmlFor="explode">Separate equipment</label><input id="explode" type="range" min="0" max="1" step="0.01" value={state.explode} onChange={e=>setState(s=>({...s,explode:Number(e.target.value)}))}/></div><button className="paths" aria-pressed={state.openServers} onClick={()=>setState(s=>({...s,openServers:!s.openServers}))}><Server size={16}/>Open servers</button><button className="paths" aria-pressed={state.paths} onClick={()=>setState(s=>({...s,paths:!s.paths}))}><Network size={16}/>Network paths</button><button className="icon reset" title="Reset view and filters" aria-label="Reset view and filters" onClick={reset}><RotateCcw size={17}/></button></div>
    <div className="viewport-footer"><span>Drag to orbit · Scroll to zoom · Click to inspect</span><span className="mono">{state.isolate?equipment.filter(e=>state.visible.includes(e.system)&&(e.id===state.selected||e.rack===state.selected)).length:equipment.filter(e=>state.visible.includes(e.system)).length} VISIBLE OBJECTS</span></div>
   </section>
  </div>
 </main>;
}
